// GENERATED by tools/embed-workflows.mjs — do not edit.
// Source: build-repo-template/
//
// The frontend writes these into each user's crucible during provisioning, and
// compares them on every visit so an outdated crucible can be re-lined with one
// click.

export const TEMPLATE_REVISION = "e53722d7e7c1";

export const TEMPLATE = {
  ".github/workflows/build.yml": `name: Thermite pour

# Only pushes to main that touch jobs/** can reach this workflow at all.
# The seed commit, workflow upgrades and README edits are filtered out here,
# before a run is even created. Cleanup commits DO touch jobs/** (they delete
# from it) and are stopped by the detect job instead.
on:
  push:
    branches: [main]
    paths:
      - 'jobs/**'

# Floor. The pour job raises exactly what it needs and nothing else.
permissions:
  contents: read

# Keyed on the commit SHA, so no two pours ever share a group and nothing can
# ever cancel anything. This exists only to collapse a duplicate push of the
# same commit. Do not change this to \${{ github.ref }} — that is the bug that
# makes a new build kill the previous one.
concurrency:
  group: thermite-pour-\${{ github.sha }}
  cancel-in-progress: false

jobs:
  detect:
    name: Read the commit
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      found:        \${{ steps.detect.outputs.found }}
      id:           \${{ steps.detect.outputs.id }}
      toolchain:    \${{ steps.detect.outputs.toolchain }}
      target:       \${{ steps.detect.outputs.target }}
      project_type: \${{ steps.detect.outputs.project_type }}
      entry:        \${{ steps.detect.outputs.entry }}
      sealed:         \${{ steps.detect.outputs.sealed }}
      sealed_source:  \${{ steps.detect.outputs.sealed_source }}
      sealed_artifact: \${{ steps.detect.outputs.sealed_artifact }}
      name:         \${{ steps.detect.outputs.name }}
      runner:       \${{ steps.detect.outputs.runner }}
      sandbox:      \${{ steps.detect.outputs.sandbox }}
      apt:          \${{ steps.detect.outputs.apt }}
      linker:       \${{ steps.detect.outputs.linker }}
      ext:          \${{ steps.detect.outputs.ext }}
      pack:         \${{ steps.detect.outputs.pack }}
      reason:       \${{ steps.detect.outputs.reason }}
    steps:
      - name: Check out the triggering commit
        uses: actions/checkout@v4
        with:
          # Explicit: build the commit that triggered this run, never the
          # branch head. If a later pour lands while this run is queued, this
          # run still compiles its own commit.
          ref: \${{ github.sha }}
          fetch-depth: 0
          persist-credentials: false

      - name: Find the pour introduced by this commit
        id: detect
        run: node scripts/detect.mjs
        env:
          THERMITE_BEFORE: \${{ github.event.before }}

  pour:
    name: \${{ needs.detect.outputs.id }} · \${{ needs.detect.outputs.target }}
    needs: detect
    if: needs.detect.outputs.found == 'true'
    runs-on: \${{ needs.detect.outputs.runner }}
    timeout-minutes: 25
    permissions:
      contents: write        # log branch + release. Nothing else.
    env:
      THERMITE_JOB:          \${{ needs.detect.outputs.id }}
      THERMITE_TOOLCHAIN:    \${{ needs.detect.outputs.toolchain }}
      THERMITE_TARGET:       \${{ needs.detect.outputs.target }}
      THERMITE_PROJECT_TYPE: \${{ needs.detect.outputs.project_type }}
      THERMITE_ENTRY:        \${{ needs.detect.outputs.entry }}
      THERMITE_NAME:         \${{ needs.detect.outputs.name }}
      THERMITE_SANDBOX:      \${{ needs.detect.outputs.sandbox }}
      THERMITE_APT:          \${{ needs.detect.outputs.apt }}
      THERMITE_LINKER:       \${{ needs.detect.outputs.linker }}
      THERMITE_EXT:          \${{ needs.detect.outputs.ext }}
      THERMITE_PACK:         \${{ needs.detect.outputs.pack }}
      THERMITE_SEALED:       \${{ needs.detect.outputs.sealed == 'true' && '1' || '0' }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out the triggering commit
        uses: actions/checkout@v4
        with:
          ref: \${{ github.sha }}
          fetch-depth: 1
          # Do not leave a credential in .git/config where a build.rs could
          # read it.
          persist-credentials: false

      - name: Open the log
        run: |
          printf 'THERMITE_STARTED_AT=%s\\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$GITHUB_ENV"
          {
            echo "THERMITE // pour \${THERMITE_JOB}"
            echo "commit  \${GITHUB_SHA}"
            echo "run     \${GITHUB_RUN_ID}"
            echo "target  \${THERMITE_TARGET}"
            echo "rust    \${THERMITE_TOOLCHAIN}"
            echo "runner  \${RUNNER_OS}/\${RUNNER_ARCH}"
            echo ""
          } | tee pour.log

      - name: Start the log relay
        # The only step before packaging that holds a token. It is handed to a
        # detached process; the compile step below runs without one.
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
        run: |
          nohup node scripts/relay.mjs \\
            --job "$THERMITE_JOB" --log pour.log --done pour.done \\
            > relay.out 2>&1 &
          echo "$!" > relay.pid
          sleep 1

      - name: Unseal the charge
        if: needs.detect.outputs.sealed_source == 'true'
        # The ONLY step in this workflow that sees the source private key. It
        # runs to completion before the compiler starts, so by the time any
        # build.rs or proc macro executes, this process no longer exists.
        env:
          THERMITE_SOURCE_KEY: \${{ secrets.THERMITE_SOURCE_KEY }}
        run: node scripts/unseal.mjs

      - name: Install cross-compilation tools
        if: runner.os == 'Linux' && needs.detect.outputs.apt != ''
        run: |
          echo "\\$ apt-get install -y \${THERMITE_APT}" | tee -a pour.log
          sudo apt-get update -qq >> pour.log 2>&1
          # shellcheck disable=SC2086
          sudo apt-get install -y -qq $THERMITE_APT >> pour.log 2>&1
          echo "" | tee -a pour.log

      - name: Compile
        id: compile
        env:
          GITHUB_TOKEN: ''
          GH_TOKEN: ''
          ACTIONS_RUNTIME_TOKEN: ''
        run: bash scripts/compile.sh

      - name: Cast the ingot
        if: success()
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
        run: node scripts/package.mjs 2>&1 | tee -a pour.log

      - name: Upload the ingot as an Actions artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: thermite-\${{ needs.detect.outputs.id }}
          path: ingot/
          retention-days: 7
          if-no-files-found: error

      - name: Shed the plaintext
        if: always() && needs.detect.outputs.sealed_source == 'true'
        # Best effort, not a guarantee: the runner VM is destroyed after the
        # job, which is the actual assurance. See the crucible README.
        run: |
          rm -rf "jobs/\${THERMITE_JOB}/source" cargo-messages.json || true
          echo "##thermite:plaintext-shed"

      - name: Close the log
        if: always()
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          CONCLUSION: \${{ job.status }}
        run: |
          if [ "$CONCLUSION" = "success" ]; then
            printf 'SUCCESS\\n' > pour.done
            printf '\\nBUILD SUCCESS\\n' >> pour.log
          elif [ "$CONCLUSION" = "cancelled" ]; then
            printf 'CANCELLED\\n' > pour.done
            printf '\\nBUILD CANCELLED\\n' >> pour.log
          else
            printf 'FAILED\\n' > pour.done
            printf '\\nBUILD FAILED\\n' >> pour.log
          fi
          # Give the relay a beat to make its final write, then make sure one
          # happened even if the relay died.
          for _ in 1 2 3 4 5 6 7 8; do
            if ! kill -0 "$(cat relay.pid 2>/dev/null)" 2>/dev/null; then break; fi
            sleep 1
          done
          kill "$(cat relay.pid 2>/dev/null)" 2>/dev/null || true
          sleep 2
          node scripts/relay.mjs --job "$THERMITE_JOB" --log pour.log --done pour.done &
          RELAY_FINAL=$!
          sleep 6
          kill "$RELAY_FINAL" 2>/dev/null || true

      - name: Summary
        if: always()
        env:
          CONCLUSION: \${{ job.status }}
        run: |
          {
            echo "### Thermite — pour \\\`\${THERMITE_JOB}\\\`"
            echo ""
            echo "| | |"
            echo "|---|---|"
            echo "| Result | \${CONCLUSION} |"
            echo "| Target | \\\`\${THERMITE_TARGET}\\\` |"
            echo "| Toolchain | \\\`\${THERMITE_TOOLCHAIN}\\\` |"
            echo "| rustc | \\\`\${THERMITE_RUSTC:-unknown}\\\` |"
            echo "| Commit | \\\`\${GITHUB_SHA}\\\` |"
          } >> "$GITHUB_STEP_SUMMARY"
`,
  ".github/workflows/cleanup.yml": `name: Thermite sweep

on:
  schedule:
    # 17 past, every 6 hours. Off the hour on purpose: the top of the hour is
    # the most congested cron slot on GitHub and is the one most likely to be
    # dropped entirely.
    - cron: '17 */6 * * *'
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'List what would be removed without removing it'
        type: boolean
        default: false

permissions:
  contents: write     # delete job directories, log files, releases and tags
  actions: read       # read run status. Never write: cleanup cannot cancel a pour.

concurrency:
  group: thermite-sweep
  cancel-in-progress: false

jobs:
  sweep:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0     # sweep needs history to date each pour

      - name: Remove spent pours
        run: node scripts/sweep.mjs
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          THERMITE_DRY_RUN: \${{ inputs.dry_run }}
`,
  "scripts/targets.mjs": `// THERMITE — authoritative target table.
//
// The website ships an advisory copy of this list. THIS file is the one that
// decides. Anything not present here is refused before a compiler is installed.
//
//   runner   : the GitHub-hosted runner label
//   mode     : 'native' | 'cross'
//   sandbox  : 'uid'   -> compile runs as a separate unprivileged local user
//              'none'  -> compile runs as the runner user (residual risk, see README)
//   apt      : extra Debian packages required for the cross linker
//   linker   : value written to CARGO_TARGET_<TRIPLE>_LINKER
//   ext      : produced binary extension
//   pack     : 'targz' | 'zip'
//   runnable : whether the produced binary can be executed on the runner

export const TARGETS = {
  'x86_64-unknown-linux-gnu': {
    runner: 'ubuntu-latest', mode: 'native', sandbox: 'uid',
    ext: '', pack: 'targz', runnable: true,
    blurb: 'Native Linux, glibc. The default pour.',
  },
  'x86_64-unknown-linux-musl': {
    runner: 'ubuntu-latest', mode: 'cross', sandbox: 'uid',
    apt: ['musl-tools'], linker: 'musl-gcc',
    ext: '', pack: 'targz', runnable: true,
    blurb: 'Static Linux binary. Runs on any distro, no glibc dependency.',
  },
  'aarch64-unknown-linux-gnu': {
    runner: 'ubuntu-latest', mode: 'cross', sandbox: 'uid',
    apt: ['gcc-aarch64-linux-gnu', 'libc6-dev-arm64-cross'],
    linker: 'aarch64-linux-gnu-gcc',
    ext: '', pack: 'targz', runnable: false,
    blurb: 'ARM64 Linux — servers, Raspberry Pi 4/5, Graviton. Cross-compiled.',
  },
  'aarch64-unknown-linux-musl': {
    runner: 'ubuntu-latest', mode: 'cross', sandbox: 'uid',
    apt: ['gcc-aarch64-linux-gnu', 'musl-tools'],
    linker: 'aarch64-linux-gnu-gcc',
    ext: '', pack: 'targz', runnable: false,
    blurb: 'Static ARM64 Linux. Cross-compiled, no runtime glibc.',
  },
  'armv7-unknown-linux-gnueabihf': {
    runner: 'ubuntu-latest', mode: 'cross', sandbox: 'uid',
    apt: ['gcc-arm-linux-gnueabihf', 'libc6-dev-armhf-cross'],
    linker: 'arm-linux-gnueabihf-gcc',
    ext: '', pack: 'targz', runnable: false,
    blurb: 'ARMv7 hard-float — Raspberry Pi 2/3, older SBCs.',
  },
  'x86_64-pc-windows-msvc': {
    runner: 'windows-latest', mode: 'native', sandbox: 'none',
    ext: '.exe', pack: 'zip', runnable: true,
    blurb: 'Native Windows with the MSVC toolchain. The one most Windows users want.',
  },
  'aarch64-pc-windows-msvc': {
    runner: 'windows-latest', mode: 'cross', sandbox: 'none',
    ext: '.exe', pack: 'zip', runnable: false,
    blurb: 'Windows on ARM. Cross-compiled from an x64 runner.',
  },
  'x86_64-pc-windows-gnu': {
    runner: 'ubuntu-latest', mode: 'cross', sandbox: 'uid',
    apt: ['gcc-mingw-w64-x86-64'], linker: 'x86_64-w64-mingw32-gcc',
    ext: '.exe', pack: 'zip', runnable: false,
    blurb: 'Windows binary built on Linux via MinGW. No MSVC runtime needed.',
  },
  'aarch64-apple-darwin': {
    runner: 'macos-latest', mode: 'native', sandbox: 'none',
    ext: '', pack: 'targz', runnable: true,
    blurb: 'Apple silicon. Native on an M-series runner. Unsigned — expect Gatekeeper.',
  },
  'x86_64-apple-darwin': {
    runner: 'macos-latest', mode: 'cross', sandbox: 'none',
    ext: '', pack: 'targz', runnable: false,
    blurb: 'Intel Mac. Cross-compiled from Apple silicon. Unsigned.',
  },
  'wasm32-unknown-unknown': {
    runner: 'ubuntu-latest', mode: 'native', sandbox: 'uid',
    ext: '.wasm', pack: 'targz', runnable: false, wasm: true,
    blurb: 'Bare WebAssembly. No std, no syscalls — for the browser and embedders.',
  },
  'wasm32-wasip1': {
    runner: 'ubuntu-latest', mode: 'native', sandbox: 'uid',
    ext: '.wasm', pack: 'targz', runnable: false, wasm: true,
    blurb: 'WASI preview 1. WebAssembly with files, args and stdio.',
  },
};

// Toolchains older than this do not know the target at all.
export const TARGET_MIN_VERSION = {
  'wasm32-wasip1': '1.78.0',
  'aarch64-apple-darwin': '1.49.0',
  'aarch64-pc-windows-msvc': '1.61.0',
};

export const TOOLCHAIN_RE =
  /^(stable|beta|nightly|nightly-\\d{4}-\\d{2}-\\d{2}|\\d+\\.\\d+(?:\\.\\d+)?)$/;

export const JOB_ID_RE = /^[0-9A-HJKMNP-TV-Z]{26}$/;

export function cmpVersion(a, b) {
  const pa = a.split('.').map(Number), pb = b.split('.').map(Number);
  for (let i = 0; i < 3; i++) {
    const d = (pa[i] || 0) - (pb[i] || 0);
    if (d) return d < 0 ? -1 : 1;
  }
  return 0;
}
`,
  "scripts/detect.mjs": `#!/usr/bin/env node
// THERMITE — detect.mjs
//
// Decide whether the commit that triggered this run introduced exactly one
// valid pour, and if so emit its validated parameters.
//
// Contract:
//   * Look at the DIFF of the triggering commit, never at the repository state.
//   * Accept only ADDED manifests. A modified manifest is not a new pour.
//   * Emit nothing unvalidated. Everything here ends up in a shell somewhere.
//   * Exit 0 when there is no pour. A cleanup commit is not a failure.

import { execFileSync } from 'node:child_process';
import { readFileSync, statSync, appendFileSync, readdirSync, existsSync } from 'node:fs';
import { join, sep } from 'node:path';
import { createHash } from 'node:crypto';
import { TARGETS, TARGET_MIN_VERSION, TOOLCHAIN_RE, JOB_ID_RE, cmpVersion } from './targets.mjs';

const LIMITS = {
  manifestBytes: 8 * 1024,
  fileBytes: 8 * 1024 * 1024,
  totalBytes: 64 * 1024 * 1024,
  fileCount: 1200,
  pathLength: 200,
  pathDepth: 24,
};

const SHA = process.env.GITHUB_SHA;
const BEFORE = process.env.THERMITE_BEFORE || '';
const OUT = process.env.GITHUB_OUTPUT;
const SUMMARY = process.env.GITHUB_STEP_SUMMARY;

const git = (...args) =>
  execFileSync('git', args, { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });

function emit(obj) {
  // GITHUB_OUTPUT is line-oriented: a stray newline in a value would let one
  // output bleed into the next. Flatten every value.
  const lines = Object.entries(obj).map(([k, v]) =>
    \`\${k}=\${String(v).replace(/[\\r\\n]+/g, ' ').slice(0, 900)}\`);
  appendFileSync(OUT, lines.join('\\n') + '\\n');
}

function note(md) {
  if (SUMMARY) appendFileSync(SUMMARY, md + '\\n');
  console.log(md.replace(/[#*\`]/g, ''));
}

function stand_down(reason) {
  emit({ found: 'false', reason });
  note(\`### Thermite\\n\\nNo pour in this commit — \${reason}. Nothing to compile.\`);
  process.exit(0);
}

function refuse(reason) {
  // A commit that looks like a pour but is not valid. Report it loudly in the
  // summary but still exit 0: the user's Actions history should not be a wall
  // of red because they hand-pushed something odd.
  emit({ found: 'false', reason });
  note(\`### Thermite — pour refused\\n\\n\${reason}\`);
  process.exit(0);
}

// ---------------------------------------------------------------- diff ------

function changedPaths() {
  const zeros = /^0{40}$/;
  if (BEFORE && !zeros.test(BEFORE) && BEFORE !== SHA) {
    try {
      git('cat-file', '-e', \`\${BEFORE}^{commit}\`);
      return parseNameStatus(git('diff', '--name-status', '-z', \`\${BEFORE}..\${SHA}\`));
    } catch { /* fall through: shallow or force-pushed history */ }
  }
  // Single-commit view. Our client only ever pushes one commit per pour, so
  // this is the correct fallback and not a degradation.
  return parseNameStatus(
    git('diff-tree', '--no-commit-id', '--name-status', '-z', '-r', '-m', SHA)
  );
}

function parseNameStatus(raw) {
  const parts = raw.split('\\0').filter(Boolean);
  const out = [];
  for (let i = 0; i < parts.length; ) {
    const status = parts[i++];
    if (/^[RC]/.test(status)) { i++; out.push({ status: 'A', path: parts[i++] }); }
    else out.push({ status: status[0], path: parts[i++] });
  }
  return out;
}

// ------------------------------------------------------------ validation ----

function safePath(p) {
  if (p.length > LIMITS.pathLength) return 'path too long';
  if (p.split('/').length > LIMITS.pathDepth) return 'path nested too deeply';
  if (!/^[A-Za-z0-9._\\/-]+$/.test(p)) return 'path contains disallowed characters';
  if (p.startsWith('/') || p.includes('//')) return 'malformed path';
  if (p.split('/').some((s) => s === '..' || s === '.' || s === '')) return 'relative segment in path';
  return null;
}

function walk(dir, base = dir, acc = []) {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const abs = join(dir, e.name);
    if (e.isSymbolicLink()) throw new Error(\`symlink in job tree: \${abs}\`);
    if (e.isDirectory()) walk(abs, base, acc);
    else if (e.isFile()) acc.push(abs.slice(base.length + 1).split(sep).join('/'));
    else throw new Error(\`irregular file in job tree: \${abs}\`);
  }
  return acc;
}

// ------------------------------------------------------------------ main ----

const changed = changedPaths();
if (!changed.length) stand_down('the commit changed nothing under jobs/');

const added = changed.filter((c) => c.status === 'A');
const manifests = added
  .map((c) => /^jobs\\/([^\\/]+)\\/manifest\\.json$/.exec(c.path))
  .filter(Boolean)
  .map((m) => m[1]);

if (manifests.length === 0) {
  const onlyDeletes = changed.every((c) => c.status === 'D');
  stand_down(onlyDeletes ? 'it only removes spent pours' : 'it adds no manifest');
}

if (manifests.length > 1) {
  refuse(
    \`This commit adds \${manifests.length} manifests. Thermite builds exactly one pour \` +
    \`per commit so that every run maps to one submission. Push them separately.\`
  );
}

const id = manifests[0];
if (!JOB_ID_RE.test(id)) refuse(\`\\\`\${id.slice(0, 40)}\\\` is not a valid pour id (ULID expected).\`);

// Every path this commit touched must live inside this one job directory.
const prefix = \`jobs/\${id}/\`;
const stray = changed.find((c) => !c.path.startsWith(prefix));
if (stray) {
  refuse(
    \`This commit also touches \\\`\${stray.path}\\\`. A pour commit may only add files \` +
    \`under \\\`\${prefix}\\\` — workflow, script and metadata changes must be pushed on their own.\`
  );
}

// ---- manifest ----
const manifestPath = \`jobs/\${id}/manifest.json\`;
if (statSync(manifestPath).size > LIMITS.manifestBytes) refuse('manifest.json is implausibly large.');

let manifest;
try { manifest = JSON.parse(readFileSync(manifestPath, 'utf8')); }
catch (e) { refuse(\`manifest.json is not valid JSON: \${e.message}\`); }

const ALLOWED_KEYS = new Set([
  'schema', 'id', 'toolchain', 'target', 'projectType', 'name',
  'entry', 'submittedAt', 'client', 'files', 'bytes', 'treeHash',
  'encryption', 'cleanup',
]);
const unknown = Object.keys(manifest).filter((k) => !ALLOWED_KEYS.has(k));
if (unknown.length) refuse(\`manifest.json has unrecognised keys: \${unknown.join(', ')}\`);

if (manifest.id !== id) refuse('manifest id does not match its directory name.');
if (manifest.schema !== 1) refuse(\`unsupported manifest schema \${manifest.schema}.\`);

const toolchain = String(manifest.toolchain || '');
if (!TOOLCHAIN_RE.test(toolchain)) refuse(\`\\\`\${toolchain.slice(0, 40)}\\\` is not a toolchain Thermite accepts.\`);

const target = String(manifest.target || '');
const spec = TARGETS[target];
if (!spec) {
  refuse(
    \`\\\`\${target.slice(0, 60)}\\\` is not a supported target. Supported: \` +
    Object.keys(TARGETS).join(', ')
  );
}

if (/^\\d/.test(toolchain)) {
  const min = TARGET_MIN_VERSION[target];
  if (min && cmpVersion(toolchain, min) < 0) {
    refuse(\`Rust \${toolchain} predates the \\\`\${target}\\\` target, which needs \${min} or newer.\`);
  }
}

const projectType = manifest.projectType;
if (projectType !== 'single' && projectType !== 'cargo') refuse('projectType must be "single" or "cargo".');

// --- encryption declaration -------------------------------------------------
// A sealed pour carries ciphertext, so its file paths cannot be checked here.
// unseal.mjs repeats every one of the checks below against the decrypted
// contents before writing a single byte to disk.
const encryption = manifest.encryption || null;
if (encryption !== null) {
  if (typeof encryption !== 'object') refuse('manifest.encryption must be an object.');
  const keys = Object.keys(encryption).filter((k) => !['source', 'artifact'].includes(k));
  if (keys.length) refuse(\`manifest.encryption has unrecognised keys: \${keys.join(', ')}\`);
  for (const side of ['source', 'artifact']) {
    const v = encryption[side];
    if (v == null) continue;
    if (typeof v !== 'object' || !/^[0-9a-f]{16}$/.test(String(v.keyId || ''))) {
      refuse(\`manifest.encryption.\${side}.keyId is not a Thermite key id.\`);
    }
  }
}
const sealedSource = !!encryption?.source;
const sealedArtifact = !!encryption?.artifact;

// Fail early and legibly rather than after a 20-minute build: the public key
// the runner needs to seal the ingot must exist at THIS commit.
if (sealedArtifact) {
  const keyPath = '.thermite/keys/artifact-public.pem';
  if (!existsSync(keyPath)) {
    refuse(
      \`This pour asks for a sealed ingot, but \\\`\${keyPath}\\\` is not present at this commit. \` +
      'Register the artifact public key from the website before pouring.');
  }
}

// --- cleanup policy ---------------------------------------------------------
const cleanup = manifest.cleanup || null;
if (cleanup !== null) {
  if (typeof cleanup !== 'object') refuse('manifest.cleanup must be an object.');
  const POLICIES = ['expire', 'onSuccess', 'onReturn'];
  if (cleanup.policy != null && !POLICIES.includes(cleanup.policy)) {
    refuse(\`manifest.cleanup.policy must be one of \${POLICIES.join(', ')}.\`);
  }
  if (cleanup.onFailure != null && !['keep', 'clean'].includes(cleanup.onFailure)) {
    refuse('manifest.cleanup.onFailure must be "keep" or "clean".');
  }
}

// ---- sources ----
let files;
try { files = walk(\`jobs/\${id}\`); }
catch (e) { refuse(e.message); }

if (files.length > LIMITS.fileCount) refuse(\`\${files.length} files exceeds the \${LIMITS.fileCount}-file ceiling.\`);

let total = 0;
for (const rel of files) {
  const bad = safePath(rel);
  if (bad) refuse(\`\\\`\${rel.slice(0, 80)}\\\`: \${bad}\`);
  if (rel.startsWith('.github/') || rel.includes('/.github/')) refuse('a pour may not contain .github/ paths.');
  const size = statSync(\`jobs/\${id}/\${rel}\`).size;
  if (size > LIMITS.fileBytes) refuse(\`\\\`\${rel}\\\` is larger than the 8 MiB per-file ceiling.\`);
  total += size;
  if (total > LIMITS.totalBytes) refuse('the pour exceeds the 64 MiB total ceiling.');
}

const sources = files.filter((f) => f !== 'manifest.json');
if (!sources.length) refuse('the pour contains no source files.');

let entry;
if (sealedSource) {
  if (!sources.includes('source.tenc')) {
    refuse('this pour declares an encrypted source but carries no source.tenc container.');
  }
  const strays = sources.filter((f) => f !== 'source.tenc');
  if (strays.length) {
    refuse(\`an encrypted pour may carry only source.tenc, but it also has: \${strays.slice(0, 5).join(', ')}\`);
  }
  entry = '';   // resolved by unseal.mjs, after decryption and validation
} else if (projectType === 'cargo') {
  const manifests_ = sources.filter((f) => f === 'source/Cargo.toml');
  if (!manifests_.length) {
    const anywhere = sources.filter((f) => f.endsWith('Cargo.toml'));
    refuse(
      anywhere.length
        ? \`Cargo.toml is at \\\`\${anywhere[0]}\\\` but must be at \\\`source/Cargo.toml\\\`. \` +
          \`Zip the project's contents, not the folder that contains it.\`
        : 'no Cargo.toml found. Submit as a single file instead, or include a Cargo.toml.'
    );
  }
  entry = 'source/Cargo.toml';
} else {
  const rs = sources.filter((f) => f.startsWith('source/') && f.endsWith('.rs'));
  if (rs.length !== 1) refuse(\`single-file pours need exactly one .rs file, found \${rs.length}.\`);
  entry = rs[0];
}
if (!sealedSource && projectType === 'single' && spec.wasm) {
  refuse(\`\\\`\${target}\\\` needs a cargo project — rustc alone cannot link a bare wasm binary usefully.\`);
}

// ---- tamper check ----
if (manifest.treeHash) {
  const h = createHash('sha256');
  for (const rel of sources.slice().sort()) {
    h.update(rel, 'utf8'); h.update('\\0');
    h.update(readFileSync(\`jobs/\${id}/\${rel}\`));
    h.update('\\0');
  }
  const actual = 'sha256:' + h.digest('hex');
  if (actual !== manifest.treeHash) {
    refuse('the source tree does not match the hash recorded at submission time.');
  }
}

const name = /^[A-Za-z0-9._ -]{1,64}$/.test(String(manifest.name || '')) ? manifest.name : id;

emit({
  found: 'true',
  id,
  toolchain,
  target,
  project_type: projectType,
  entry,
  sealed: String(sealedSource || sealedArtifact),
  sealed_source: String(sealedSource),
  sealed_artifact: String(sealedArtifact),
  name,
  runner: spec.runner,
  mode: spec.mode,
  sandbox: spec.sandbox,
  apt: (spec.apt || []).join(' '),
  linker: spec.linker || '',
  ext: spec.ext,
  pack: spec.pack,
  files: String(sources.length),
  bytes: String(total),
  submitted_at: /^\\d{4}-\\d{2}-\\d{2}T/.test(String(manifest.submittedAt || ''))
    ? manifest.submittedAt : new Date().toISOString(),
});

note(
  \`### Thermite — pour \\\`\${id}\\\`\\n\\n\` +
  \`| | |\\n|---|---|\\n\` +
  \`| Toolchain | \\\`\${toolchain}\\\` |\\n| Target | \\\`\${target}\\\` |\\n\` +
  \`| Kind | \${projectType === 'cargo' ? 'cargo project' : 'single file'} |\\n\` +
  \`| Sealed | \${sealedSource ? 'source' : '—'}\${sealedArtifact ? (sealedSource ? ' + ingot' : 'ingot') : ''} |\\n\` +
  \`| Size | \${(total / 1024).toFixed(1)} KiB |\\n\` +
  \`| Runner | \\\`\${spec.runner}\\\` (\${spec.mode}) |\\n\`
);
`,
  "scripts/tenc.mjs": `// THERMITE — THERMITE-ENC v1, runner side.
//
// The exact format implemented in js/crypto.js. Change one, change both.
//
//   ┌────────────┬─────────────┬──────────────┬──────────────────────────┐
//   │ "THRMENC1" │ u32be hdrLen│ header (JSON)│ ciphertext ‖ GCM tag     │
//   └────────────┴─────────────┴──────────────┴──────────────────────────┘
//
// Web Crypto appends the 16-byte GCM tag to the ciphertext; Node keeps it
// separate, so it is split off on decrypt and appended on encrypt.

import {
  publicEncrypt, privateDecrypt, constants, randomBytes,
  createCipheriv, createDecipheriv, createHash, createPublicKey,
} from 'node:crypto';
import { gzipSync, gunzipSync } from 'node:zlib';

export const FORMAT = 'THERMITE-ENC';
export const VERSION = 1;
export const MAGIC = 'THRMENC1';
export const KEM_ALG = 'RSA-OAEP-4096-SHA256';
export const AEAD_ALG = 'AES-256-GCM';
const TAG_BYTES = 16;

export class TencError extends Error {}

export function keyIdOfPublicPem(pem) {
  const spki = createPublicKey(pem).export({ type: 'spki', format: 'der' });
  return createHash('sha256').update(spki).digest('hex').slice(0, 16);
}

function assemble(header, ciphertext) {
  const headerBytes = Buffer.from(JSON.stringify(header), 'utf8');
  const prefix = Buffer.alloc(12);
  prefix.write(MAGIC, 0, 'ascii');
  prefix.writeUInt32BE(headerBytes.length, 8);
  const aad = Buffer.concat([prefix, headerBytes]);
  return { aad, container: Buffer.concat([aad, ciphertext]) };
}

export function parse(container) {
  const buf = Buffer.isBuffer(container) ? container : Buffer.from(container);
  if (buf.length < 13) throw new TencError('not a Thermite container');
  if (buf.subarray(0, 8).toString('ascii') !== MAGIC) throw new TencError('not a THERMITE-ENC container');
  const headerLen = buf.readUInt32BE(8);
  if (headerLen > 65536 || 12 + headerLen > buf.length) throw new TencError('malformed container header');
  const header = JSON.parse(buf.subarray(12, 12 + headerLen).toString('utf8'));
  if (header.format !== FORMAT || header.version !== VERSION) {
    throw new TencError(\`unsupported container \${header.format} v\${header.version}\`);
  }
  return { header, aad: buf.subarray(0, 12 + headerLen), ciphertext: buf.subarray(12 + headerLen) };
}

/**
 * @param {Buffer} plaintext
 * @param {string} publicPem  recipient's SPKI PEM
 * @param {{purpose:string, jobId:string, compression?:'gzip'|'none', note?:string}} ctx
 */
export function seal(plaintext, publicPem, ctx) {
  const useGzip = ctx.compression !== 'none';
  const body = useGzip ? gzipSync(plaintext, { level: 9 }) : plaintext;

  const cek = randomBytes(32);
  const iv = randomBytes(12);
  const wrapped = publicEncrypt(
    { key: publicPem, padding: constants.RSA_PKCS1_OAEP_PADDING, oaepHash: 'sha256' },
    cek);

  const header = {
    format: FORMAT,
    version: VERSION,
    purpose: ctx.purpose,
    jobId: ctx.jobId || null,
    kem: { alg: KEM_ALG, keyId: keyIdOfPublicPem(publicPem), wrappedKey: wrapped.toString('base64') },
    aead: { alg: AEAD_ALG, iv: iv.toString('base64'), tagBits: 128 },
    payload: { compression: useGzip ? 'gzip' : 'none', bytes: plaintext.length },
    createdAt: new Date().toISOString(),
    ...(ctx.note ? { note: ctx.note } : {}),
  };

  const headerBytes = Buffer.from(JSON.stringify(header), 'utf8');
  const prefix = Buffer.alloc(12);
  prefix.write(MAGIC, 0, 'ascii');
  prefix.writeUInt32BE(headerBytes.length, 8);
  const aad = Buffer.concat([prefix, headerBytes]);

  const cipher = createCipheriv('aes-256-gcm', cek, iv, { authTagLength: TAG_BYTES });
  cipher.setAAD(aad);
  const ct = Buffer.concat([cipher.update(body), cipher.final()]);
  // Match Web Crypto's layout: tag appended to the ciphertext.
  return Buffer.concat([aad, ct, cipher.getAuthTag()]);
}

/**
 * @param {Buffer} container
 * @param {string} privatePem  PKCS#8 PEM
 */
export function unseal(container, privatePem) {
  const { header, aad, ciphertext } = parse(container);
  if (header.kem?.alg !== KEM_ALG) throw new TencError(\`unsupported key wrapping \${header.kem?.alg}\`);
  if (header.aead?.alg !== AEAD_ALG) throw new TencError(\`unsupported cipher \${header.aead?.alg}\`);
  if (ciphertext.length < TAG_BYTES) throw new TencError('container truncated');

  let cek;
  try {
    cek = privateDecrypt(
      { key: privatePem, padding: constants.RSA_PKCS1_OAEP_PADDING, oaepHash: 'sha256' },
      Buffer.from(header.kem.wrappedKey, 'base64'));
  } catch {
    throw new TencError(
      'the content key could not be unwrapped — the private key in THERMITE_SOURCE_KEY does not match ' +
      \`the public key this pour was sealed for (\${header.kem.keyId})\`);
  }

  const tag = ciphertext.subarray(ciphertext.length - TAG_BYTES);
  const ct = ciphertext.subarray(0, ciphertext.length - TAG_BYTES);
  const decipher = createDecipheriv('aes-256-gcm', cek, Buffer.from(header.aead.iv, 'base64'),
    { authTagLength: TAG_BYTES });
  decipher.setAAD(aad);
  decipher.setAuthTag(tag);

  let body;
  try { body = Buffer.concat([decipher.update(ct), decipher.final()]); }
  catch { throw new TencError('authentication failed — the container was modified or corrupted'); }

  if (header.payload?.compression === 'gzip') body = gunzipSync(body);
  if (header.payload?.bytes != null && body.length !== header.payload.bytes) {
    throw new TencError('decrypted payload length does not match the header');
  }
  return { bytes: body, header };
}
`,
  "scripts/unseal.mjs": `#!/usr/bin/env node
// THERMITE — unseal.mjs
//
// Decrypt a sealed charge into jobs/<id>/source/.
//
// Two things matter here.
//
// 1. detect.mjs could not inspect this pour's file paths, because they were
//    ciphertext. So every check detect.mjs would have made is made HERE, after
//    decryption and before anything touches the disk. An encrypted pour is not
//    a less-validated pour.
//
// 2. This script runs in its own workflow step, and that step is the only place
//    THERMITE_SOURCE_KEY exists. The step finishes before the compiler starts,
//    so by the time any build.rs or proc macro executes, the process that held
//    the source private key is gone.

import { readFileSync, writeFileSync, mkdirSync, rmSync, appendFileSync } from 'node:fs';
import { dirname, join, resolve, sep } from 'node:path';
import { unseal, TencError } from './tenc.mjs';

const LIMITS = {
  fileBytes: 8 * 1024 * 1024,
  totalBytes: 64 * 1024 * 1024,
  fileCount: 1200,
  pathLength: 200,
  pathDepth: 24,
};

const JOB = process.env.THERMITE_JOB;
const KIND = process.env.THERMITE_PROJECT_TYPE;
const KEY = process.env.THERMITE_SOURCE_KEY;

if (!/^[0-9A-HJKMNP-TV-Z]{26}$/.test(JOB || '')) fail('invalid job id');

const jobDir = \`jobs/\${JOB}\`;
const outDir = join(jobDir, 'source');
const sealedPath = join(jobDir, 'source.tenc');

function fail(message, code = 92) {
  const text = \`\\nThermite could not unseal this pour: \${message}\\n\`;
  process.stdout.write(text);
  try { appendFileSync('pour.log', text); } catch {}
  try { appendFileSync('pour.done', ''); } catch {}
  process.exit(code);
}

if (!KEY || !KEY.includes('PRIVATE KEY')) {
  fail(
    'the repository secret THERMITE_SOURCE_KEY is missing or is not a PEM private key.\\n' +
    'Add it under Settings → Secrets and variables → Actions, using the private key\\n' +
    'Thermite showed you during encryption setup. Thermite never sees this value.');
}

let container;
try { container = readFileSync(sealedPath); }
catch { fail(\`\${sealedPath} is missing. This pour claims to be encrypted but carries no sealed charge.\`); }

let result;
try { result = unseal(container, KEY); }
catch (e) {
  fail(e instanceof TencError ? e.message : \`decryption failed (\${e.code || e.message})\`);
}

if (result.header.purpose !== 'source') fail(\`this container is a "\${result.header.purpose}" container, not a source charge\`);
if (result.header.jobId && result.header.jobId !== JOB) {
  fail(\`this charge was sealed for pour \${result.header.jobId}, not \${JOB}\`);
}

let charge;
try { charge = JSON.parse(result.bytes.toString('utf8')); }
catch { fail('the decrypted charge is not readable'); }
if (charge.kind !== 'thermite-charge' || charge.version !== 1) fail('unrecognised charge format');
if (!Array.isArray(charge.files) || !charge.files.length) fail('the charge contains no files');
if (charge.files.length > LIMITS.fileCount) fail(\`the charge holds \${charge.files.length} files, over the \${LIMITS.fileCount} ceiling\`);

// ---------------------------------------------------- validate, then write --

const root = resolve(outDir);
let total = 0;
const written = [];

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

for (const f of charge.files) {
  const p = String(f.path || '');
  if (p.length > LIMITS.pathLength) fail(\`"\${p.slice(0, 60)}…": path too long\`);
  if (p.split('/').length > LIMITS.pathDepth) fail(\`"\${p}": nested too deeply\`);
  if (!/^[A-Za-z0-9._\\/-]+$/.test(p)) fail(\`"\${p}": path contains characters the build refuses\`);
  if (p.startsWith('/') || p.includes('//')) fail(\`"\${p}": malformed path\`);
  if (p.split('/').some((s) => s === '..' || s === '.' || s === '')) fail(\`"\${p}": relative segment in path\`);
  if (p === '.github' || p.startsWith('.github/') || p.includes('/.github/')) {
    fail(\`"\${p}": a pour may not carry .github/ paths\`);
  }

  const target = resolve(root, p);
  // Belt and braces: even after the checks above, refuse anything that does not
  // resolve inside the job's source directory.
  if (target !== root && !target.startsWith(root + sep)) fail(\`"\${p}": escapes the pour directory\`);

  const bytes = Buffer.from(String(f.data || ''), 'base64');
  if (bytes.length > LIMITS.fileBytes) fail(\`"\${p}": larger than the 8 MiB per-file ceiling\`);
  total += bytes.length;
  if (total > LIMITS.totalBytes) fail('the charge expands past the 64 MiB ceiling');

  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, bytes);
  written.push(p);
}

// ------------------------------------------------------------- entrypoint --

let entry;
if (KIND === 'cargo') {
  if (!written.includes('Cargo.toml')) {
    fail('no Cargo.toml at the root of the sealed project');
  }
  entry = 'source/Cargo.toml';
} else {
  const rs = written.filter((f) => f.endsWith('.rs'));
  if (rs.length !== 1) fail(\`single-file pours need exactly one .rs file, the charge has \${rs.length}\`);
  entry = \`source/\${rs[0]}\`;
}

// The sealed container is left in the repository; only the plaintext is
// ephemeral, and the workflow removes it after the ingot is cast.
// A distinct name on purpose: job-level \`env:\` wins over anything written to
// GITHUB_ENV, so reusing THERMITE_ENTRY here would be silently overridden by
// the empty value detect.mjs emits for sealed pours.
appendFileSync(process.env.GITHUB_ENV, \`THERMITE_ENTRY_UNSEALED=\${entry}\\n\`);

// Actions logs on a public repository are publicly readable, so nothing about
// the decrypted contents — not even file names — is printed anywhere.
const summary =
  \`Unsealed \${written.length} file(s), \${(total / 1024).toFixed(1)} KiB, \` +
  \`sealed for key \${result.header.kem.keyId}.\\n\`;
process.stdout.write(summary);
appendFileSync('pour.log', \`##thermite:unsealed \${written.length}\\n\${summary}\`);
`,
  "scripts/relay.mjs": `#!/usr/bin/env node
// THERMITE — relay.mjs
//
// GitHub's Actions log endpoint redirects to a blob host with no CORS headers,
// so a browser can never read a running job's logs. This process solves that by
// pushing the log into the repository itself, where the Contents API — which is
// CORS-clean — can serve it to the page every couple of seconds.
//
// Runs detached, beside the compiler, holding the only copy of the token.
// The compiler itself is started with an empty GITHUB_TOKEN.
//
//   node scripts/relay.mjs --job <ULID> --log pour.log --done pour.done

import { readFileSync, existsSync, statSync, openSync, readSync, closeSync } from 'node:fs';
import { seal } from './tenc.mjs';

const args = Object.fromEntries(
  process.argv.slice(2).reduce((a, v, i, arr) => (v.startsWith('--') ? [...a, [v.slice(2), arr[i + 1]]] : a), [])
);

const JOB = args.job;
const LOG = args.log || 'pour.log';
const DONE = args.done || 'pour.done';
const BRANCH = 'crucible-logs';
const API = process.env.GITHUB_API_URL || 'https://api.github.com';
const REPO = process.env.GITHUB_REPOSITORY;
const TOKEN = process.env.GITHUB_TOKEN;
const INTERVAL = 2500;
const MAX_BYTES = 640 * 1024; // keep the tail; the release carries the full log

// On a sealed pour the log is encrypted with the ARTIFACT public key before it
// is published, because compiler diagnostics quote source and this branch is
// public. The state file stays plaintext: it carries only metadata.
const ARTIFACT_KEY_PATH = '.thermite/keys/artifact-public.pem';
const artifactKey = existsSync(ARTIFACT_KEY_PATH) && process.env.THERMITE_SEALED === '1'
  ? readFileSync(ARTIFACT_KEY_PATH, 'utf8')
  : null;

if (!/^[0-9A-HJKMNP-TV-Z]{26}$/.test(JOB || '')) { console.error('relay: bad job id'); process.exit(1); }
if (!TOKEN || !REPO) { console.error('relay: missing environment'); process.exit(1); }

const shas = new Map();

async function api(path, init = {}) {
  const res = await fetch(\`\${API}\${path}\`, {
    ...init,
    headers: {
      Authorization: \`Bearer \${TOKEN}\`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'User-Agent': 'thermite-relay',
      ...(init.body ? { 'Content-Type': 'application/json' } : {}),
    },
  });
  return res;
}

async function put(path, content, message) {
  for (let attempt = 0; attempt < 5; attempt++) {
    if (!shas.has(path)) {
      const probe = await api(\`/repos/\${REPO}/contents/\${path}?ref=\${BRANCH}\`);
      if (probe.ok) shas.set(path, (await probe.json()).sha);
    }
    const body = {
      message,
      branch: BRANCH,
      content: Buffer.from(content, 'utf8').toString('base64'),
      ...(shas.has(path) ? { sha: shas.get(path) } : {}),
    };
    const res = await api(\`/repos/\${REPO}/contents/\${path}\`, { method: 'PUT', body: JSON.stringify(body) });
    if (res.ok) { shas.set(path, (await res.json()).content.sha); return true; }
    // 409/422: another pour moved the branch under us, or our sha is stale.
    if (res.status === 409 || res.status === 422 || res.status === 404) {
      shas.delete(path);
      await sleep(200 + Math.random() * 600 * (attempt + 1));
      continue;
    }
    if (res.status === 403 || res.status === 429) {
      const wait = Number(res.headers.get('retry-after') || 5);
      await sleep(wait * 1000);
      continue;
    }
    console.error(\`relay: \${res.status} writing \${path}\`);
    return false;
  }
  return false;
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

// Phase is inferred only from evidence in the real output. Nothing is guessed
// and nothing advances on a timer.
function phaseOf(text) {
  if (/^##thermite:packaged/m.test(text)) return 'CAST';
  if (/^\\s*Finished\\b/m.test(text) || /^##thermite:linking/m.test(text)) return 'LINK';
  if (/^\\s*Compiling\\b/m.test(text) || /^##thermite:compiling/m.test(text)) return 'COMPILE';
  if (/^##thermite:toolchain-ready/m.test(text)) return 'IGNITE';
  return 'INGEST';
}

function tail(path) {
  const size = statSync(path).size;
  const start = Math.max(0, size - MAX_BYTES);
  const fd = openSync(path, 'r');
  try {
    const buf = Buffer.alloc(size - start);
    readSync(fd, buf, 0, buf.length, start);
    const text = buf.toString('utf8');
    return { size, text: start > 0 ? \`… \${start} earlier bytes withheld; full log ships with the ingot …\\n\${text}\` : text };
  } finally { closeSync(fd); }
}

let lastSize = -1;
let lastPhase = '';
const startedAt = new Date().toISOString();
let lines = 0;

async function flush(final) {
  if (!existsSync(LOG)) return;
  const { size, text } = tail(LOG);
  const phase = final ? (existsSync(DONE) ? readFileSync(DONE, 'utf8').trim() : 'UNKNOWN') : phaseOf(text);
  if (!final && size === lastSize && phase === lastPhase) return;

  const nl = (text.match(/\\n/g) || []).length;
  const rate = Math.max(0, nl - lines);
  lines = nl;

  const body = text + (final ? \`\\n##thermite:end:\${phase}\\n\` : '');
  if (artifactKey) {
    // Base64 of the container, so the branch holds text and the browser can
    // fetch it with the raw media type like any other log.
    const sealed = seal(Buffer.from(body, 'utf8'), artifactKey,
      { purpose: 'log', jobId: JOB, note: 'thermite live log' });
    await put(\`logs/\${JOB}.log.tenc\`, sealed.toString('base64') + '\\n',
      \`thermite: pour \${JOB} \${final ? 'final' : 'stream'} [skip ci]\`);
  } else {
    await put(\`logs/\${JOB}.log\`, body,
      \`thermite: pour \${JOB} \${final ? 'final' : 'stream'} [skip ci]\`);
  }

  await put(\`logs/\${JOB}.state.json\`, JSON.stringify({
    job: JOB,
    phase: final ? phase : phase,
    live: !final,
    startedAt,
    updatedAt: new Date().toISOString(),
    bytes: size,
    lines: nl,
    lineRate: rate,
    runner: \`\${process.env.RUNNER_OS}/\${process.env.RUNNER_ARCH}\`,
    sealed: !!artifactKey,
    runId: process.env.GITHUB_RUN_ID,
    sha: process.env.GITHUB_SHA,
    rustc: process.env.THERMITE_RUSTC || null,
    cargo: process.env.THERMITE_CARGO || null,
    target: process.env.THERMITE_TARGET || null,
    toolchain: process.env.THERMITE_TOOLCHAIN || null,
  }, null, 2) + '\\n', \`thermite: pour \${JOB} state [skip ci]\`);

  lastSize = size;
  lastPhase = phase;
}

process.on('SIGTERM', async () => { await flush(true); process.exit(0); });

(async () => {
  while (!existsSync(DONE)) {
    try { await flush(false); } catch (e) { console.error('relay:', e.message); }
    await sleep(INTERVAL);
  }
  await sleep(400);           // let the last writes land on disk
  try { await flush(true); } catch (e) { console.error('relay final:', e.message); }
})();
`,
  "scripts/package.mjs": `#!/usr/bin/env node
// THERMITE — package.mjs
//
// Turn whatever the compiler produced into an ingot: one archive, a checksum,
// and a record of exactly how it was made. Then publish it twice — as an
// Actions artifact (done by the workflow) and as a release asset, because a
// public repo's release assets have plain unauthenticated download URLs and
// are therefore the only artifact a static page can actually hand to a user.

import { execFileSync } from 'node:child_process';
import {
  readFileSync, writeFileSync, mkdirSync, copyFileSync, existsSync,
  statSync, readdirSync, unlinkSync, rmSync,
} from 'node:fs';
import { basename, join } from 'node:path';
import { createHash } from 'node:crypto';
import { seal, keyIdOfPublicPem } from './tenc.mjs';

const env = process.env;
const JOB = env.THERMITE_JOB;
const TARGET = env.THERMITE_TARGET;
const TOOLCHAIN = env.THERMITE_TOOLCHAIN;
const KIND = env.THERMITE_PROJECT_TYPE;
const EXT = env.THERMITE_EXT || '';
const PACK = env.THERMITE_PACK || 'targz';
const NAME = (env.THERMITE_NAME || JOB).replace(/[^A-Za-z0-9._-]/g, '_');
const API = env.GITHUB_API_URL || 'https://api.github.com';
const REPO = env.GITHUB_REPOSITORY;
const TOKEN = env.GITHUB_TOKEN;

const OUT = 'ingot';
mkdirSync(OUT, { recursive: true });

// ------------------------------------------------------- locate binaries ----

function fromCargoMessages(file) {
  if (!existsSync(file)) return [];
  const found = [];
  for (const line of readFileSync(file, 'utf8').split('\\n')) {
    if (!line.startsWith('{')) continue;
    let m; try { m = JSON.parse(line); } catch { continue; }
    if (m.reason === 'compiler-artifact' && m.executable) found.push(m.executable);
    if (m.reason === 'compiler-artifact' && !m.executable && m.filenames) {
      for (const f of m.filenames) if (f.endsWith('.wasm')) found.push(f);
    }
  }
  return [...new Set(found)];
}

function diagnostics(file) {
  if (!existsSync(file)) return [];
  const out = [];
  for (const line of readFileSync(file, 'utf8').split('\\n')) {
    if (!line.startsWith('{')) continue;
    let m; try { m = JSON.parse(line); } catch { continue; }
    if (m.reason !== 'compiler-message' || !m.message) continue;
    const d = m.message;
    if (d.level !== 'error' && d.level !== 'warning') continue;
    const span = (d.spans || []).find((s) => s.is_primary) || (d.spans || [])[0];
    out.push({
      level: d.level,
      code: d.code?.code || null,
      message: d.message,
      file: span?.file_name || null,
      line: span?.line_start ?? null,
      column: span?.column_start ?? null,
      rendered: (d.rendered || '').slice(0, 4000),
    });
  }
  return out.slice(0, 200);
}

let binaries = [];
if (KIND === 'cargo') {
  binaries = fromCargoMessages('cargo-messages.json');
  if (!binaries.length) {
    // Fallback: scan the target directory for anything executable-looking.
    const dir = join('source', 'target', TARGET, 'release');
    if (existsSync(dir)) {
      for (const f of readdirSync(dir, { withFileTypes: true })) {
        if (!f.isFile()) continue;
        const p = join(dir, f.name);
        if (EXT ? f.name.endsWith(EXT) : !/\\.(d|rlib|rmeta|so|dylib|pdb)$/.test(f.name)) {
          try { if (statSync(p).mode & 0o111 || EXT) binaries.push(p); } catch {}
        }
      }
    }
  }
} else {
  const single = join('out', NAME + EXT);
  if (existsSync(single)) binaries.push(single);
}

binaries = binaries.filter((b) => existsSync(b));
if (!binaries.length) {
  console.error('##thermite:no-artifact');
  writeFileSync('pour-result.json', JSON.stringify({ ok: false, reason: 'no executable produced' }));
  process.exit(1);
}

// ----------------------------------------------------------- assemble -------

const sums = [];
for (const b of binaries) {
  const dest = join(OUT, basename(b));
  copyFileSync(b, dest);
  const hash = createHash('sha256').update(readFileSync(dest)).digest('hex');
  sums.push({ file: basename(b), sha256: hash, bytes: statSync(dest).size });
}
writeFileSync(join(OUT, 'SHA256SUMS'), sums.map((s) => \`\${s.sha256}  \${s.file}\`).join('\\n') + '\\n');

const record = {
  job: JOB,
  name: NAME,
  toolchain: TOOLCHAIN,
  requestedTarget: TARGET,
  projectType: KIND,
  rustc: env.THERMITE_RUSTC || null,
  cargo: env.THERMITE_CARGO || null,
  runner: { os: env.RUNNER_OS, arch: env.RUNNER_ARCH, image: env.ImageOS || null },
  commit: env.GITHUB_SHA,
  runId: env.GITHUB_RUN_ID,
  startedAt: env.THERMITE_STARTED_AT || null,
  finishedAt: new Date().toISOString(),
  durationSeconds: env.THERMITE_STARTED_AT
    ? Math.round((Date.now() - Date.parse(env.THERMITE_STARTED_AT)) / 1000) : null,
  binaries: sums,
  warnings: diagnostics('cargo-messages.json').filter((d) => d.level === 'warning').length,
};
writeFileSync(join(OUT, 'pour.json'), JSON.stringify(record, null, 2) + '\\n');
if (existsSync('pour.log')) copyFileSync('pour.log', join(OUT, 'pour.log'));

const archive = PACK === 'zip' ? \`thermite-\${JOB}.zip\` : \`thermite-\${JOB}.tar.gz\`;
if (PACK === 'zip') {
  if (process.platform === 'win32') execFileSync('tar', ['-a', '-c', '-f', archive, '-C', OUT, '.'], { stdio: 'inherit' });
  else execFileSync('zip', ['-r', '-q', '-j', archive, OUT], { stdio: 'inherit' });
} else {
  execFileSync('tar', ['-czf', archive, '-C', OUT, '.'], { stdio: 'inherit' });
}
const archiveHash = createHash('sha256').update(readFileSync(archive)).digest('hex');

// ------------------------------------------------------------ seal ---------
// If the pour registered an artifact public key, the ingot is sealed here and
// ONLY the sealed container leaves this runner. The plaintext archive is
// removed, and nothing plaintext is uploaded to a release or an Actions
// artifact. The matching private key exists only in the user's browser.
const ARTIFACT_KEY_PATH = '.thermite/keys/artifact-public.pem';
let upload = archive;
let sealedKeyId = null;

if (env.THERMITE_SEALED === '1') {
  if (!existsSync(ARTIFACT_KEY_PATH)) {
    console.error('##thermite:seal-failed no artifact public key in the crucible');
    writeFileSync('pour-result.json', JSON.stringify({ ok: false, reason: 'artifact public key missing' }));
    process.exit(1);
  }
  const pem = readFileSync(ARTIFACT_KEY_PATH, 'utf8');
  sealedKeyId = keyIdOfPublicPem(pem);
  const container = seal(readFileSync(archive), pem,
    { purpose: 'artifact', jobId: JOB, compression: 'none', note: \`thermite ingot \${archive}\` });
  upload = \`thermite-\${JOB}.tenc\`;
  writeFileSync(upload, container);
  unlinkSync(archive);
  // The plaintext ingot directory would otherwise be picked up by the Actions
  // artifact upload step.
  rmSync(OUT, { recursive: true, force: true });
  mkdirSync(OUT, { recursive: true });
  copyFileSync(upload, join(OUT, upload));
  console.log(\`##thermite:sealed \${upload} for key \${sealedKeyId}\`);
}

console.log(\`##thermite:packaged \${upload} sha256=\${archiveHash}\`);

// ------------------------------------------------------------ release -------

async function api(path, init = {}, base = API) {
  return fetch(path.startsWith('http') ? path : \`\${base}\${path}\`, {
    ...init,
    headers: {
      Authorization: \`Bearer \${TOKEN}\`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'User-Agent': 'thermite-package',
      ...(init.headers || {}),
    },
  });
}

const tag = \`pour-\${JOB}\`;
let release;
const existing = await api(\`/repos/\${REPO}/releases/tags/\${tag}\`);
if (existing.ok) {
  release = await existing.json();
} else {
  const res = await api(\`/repos/\${REPO}/releases\`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      tag_name: tag,
      target_commitish: env.GITHUB_SHA,
      name: \`\${NAME} · \${TARGET}\`,
      body: [
        \`Pour \\\`\${JOB}\\\`\`, '',
        \`- toolchain \\\`\${TOOLCHAIN}\\\` (\${record.rustc || 'unknown'})\`,
        \`- target \\\`\${TARGET}\\\`\`,
        \`- runner \\\`\${record.runner.os}/\${record.runner.arch}\\\`\`,
        \`- sha256 of the plaintext archive \\\`\${archiveHash}\\\`\`,
        ...(sealedKeyId ? ['', \`Sealed with THERMITE-ENC v1 for artifact key \\\`\${sealedKeyId}\\\`.\`,
          'Only the holder of the matching private key can open it. Thermite does not have a copy.'] : []),
        '',
        'Cleaned up automatically about 24 hours after the pour.',
      ].join('\\n'),
      draft: false,
      prerelease: false,
      make_latest: 'false',
    }),
  });
  if (!res.ok) {
    console.error(\`##thermite:release-failed \${res.status} \${await res.text()}\`);
    writeFileSync('pour-result.json', JSON.stringify({ ok: true, archive: upload, archiveHash, release: null, record }));
    process.exit(0); // the Actions artifact still exists; do not fail the pour
  }
  release = await res.json();
}

async function uploadAsset(file) {
  const url = release.upload_url.replace(/\\{.*$/, \`?name=\${encodeURIComponent(basename(file))}\`);
  const res = await api(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/octet-stream' },
    body: readFileSync(file),
  });
  if (!res.ok) { console.error(\`##thermite:asset-failed \${basename(file)} \${res.status}\`); return null; }
  return (await res.json()).browser_download_url;
}

const assetUrl = await uploadAsset(upload);

// The build log quotes source in its diagnostics, so on a sealed pour it is
// sealed with the same artifact key rather than published in the clear.
if (existsSync('pour.log')) {
  if (sealedKeyId) {
    const pem = readFileSync(ARTIFACT_KEY_PATH, 'utf8');
    writeFileSync('pour.log.tenc', seal(readFileSync('pour.log'), pem,
      { purpose: 'log', jobId: JOB, note: 'thermite build log' }));
    await uploadAsset('pour.log.tenc');
  } else {
    await uploadAsset('pour.log');
  }
}

writeFileSync('pour-result.json', JSON.stringify({
  ok: true, archive: upload, archiveHash, tag, sealedFor: sealedKeyId,
  downloadUrl: assetUrl, releaseUrl: release.html_url, record,
}, null, 2));

console.log(\`##thermite:ingot \${assetUrl || '(release asset unavailable)'}\`);
`,
  "scripts/compile.sh": `#!/usr/bin/env bash
# THERMITE — compile.sh
#
# Runs the actual compiler. Everything it needs arrives through THERMITE_* env
# vars that detect.mjs already validated; nothing is interpolated from the
# commit into a shell.
#
# GITHUB_TOKEN is deliberately absent from this script's environment. On Linux
# the compile additionally runs as a separate unprivileged user, so untrusted
# build.rs / proc-macro code cannot read the relay process's environment via
# /proc. On Windows and macOS runners that boundary does not exist — see
# README.md, "What a pour can and cannot do".

set -uo pipefail

JOB_DIR="jobs/\${THERMITE_JOB}"
SRC="\${JOB_DIR}/source"
# On a sealed pour the entrypoint is not known until unseal.mjs has decrypted
# and validated the charge, so it arrives under a separate name.
ENTRY="\${THERMITE_ENTRY_UNSEALED:-\${THERMITE_ENTRY:-}}"
LOG="pour.log"
TRIPLE_ENV=""

# On a sealed pour the log is encrypted before it is published, but the Actions
# job log is PUBLIC on a public repository. So when a pour is sealed, compiler
# output goes only into pour.log — never to stdout. Markers carry no source and
# are always shown, so the run is still legible on GitHub.
if [ "\${THERMITE_SEALED:-0}" = "1" ]; then
  pipe() { tee -a "$LOG" >/dev/null; }
else
  pipe() { tee -a "$LOG"; }
fi
say()  { printf '%s\\n' "$*" | pipe; }
# On a sealed pour \`pipe\` swallows stdout, so the marker is echoed separately to
# keep the run legible on GitHub. On a plain pour \`pipe\` already writes to
# stdout — echoing again is what was printing every marker twice.
if [ "\${THERMITE_SEALED:-0}" = "1" ]; then
  mark() { printf '##thermite:%s\\n' "$*" | pipe; printf '##thermite:%s\\n' "$*"; }
else
  mark() { printf '##thermite:%s\\n' "$*" | pipe; }
fi

# --------------------------------------------------------------- toolchain --

say "\\$ rustup toolchain install \${THERMITE_TOOLCHAIN} --profile minimal"
if ! rustup toolchain install "\${THERMITE_TOOLCHAIN}" --profile minimal --no-self-update 2>&1 | pipe; then
  say ""
  say "Rust \${THERMITE_TOOLCHAIN} could not be installed. Check that this version exists."
  exit 90
fi

say ""
say "\\$ rustup target add \${THERMITE_TARGET} --toolchain \${THERMITE_TOOLCHAIN}"
if ! rustup target add "\${THERMITE_TARGET}" --toolchain "\${THERMITE_TOOLCHAIN}" 2>&1 | pipe; then
  say ""
  say "Rust \${THERMITE_TOOLCHAIN} has no standard library for \${THERMITE_TARGET}."
  say "Choose a newer toolchain, or a target this toolchain supports."
  exit 91
fi

THERMITE_RUSTC="$(rustc "+\${THERMITE_TOOLCHAIN}" -V 2>/dev/null || echo unknown)"
THERMITE_CARGO="$(cargo "+\${THERMITE_TOOLCHAIN}" -V 2>/dev/null || echo unknown)"
export THERMITE_RUSTC THERMITE_CARGO
{
  printf 'THERMITE_RUSTC=%s\\n' "$THERMITE_RUSTC"
  printf 'THERMITE_CARGO=%s\\n' "$THERMITE_CARGO"
} >> "$GITHUB_ENV"

say ""
say "  \${THERMITE_RUSTC}"
say "  \${THERMITE_CARGO}"
say "  runner \${RUNNER_OS}/\${RUNNER_ARCH}"
mark "toolchain-ready"

# ------------------------------------------------------------ cross linker --

if [ -n "\${THERMITE_LINKER:-}" ]; then
  TRIPLE_ENV="CARGO_TARGET_$(printf '%s' "$THERMITE_TARGET" | tr 'a-z-' 'A-Z_')_LINKER"
  export "\${TRIPLE_ENV}=\${THERMITE_LINKER}"
  printf '%s=%s\\n' "$TRIPLE_ENV" "$THERMITE_LINKER" >> "$GITHUB_ENV"
  say "  cross linker \${THERMITE_LINKER}"
  case "$THERMITE_TARGET" in
    x86_64-unknown-linux-musl) export CC_x86_64_unknown_linux_musl=musl-gcc ;;
    aarch64-unknown-linux-*)   export CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc ;;
    armv7-unknown-linux-*)     export CC_armv7_unknown_linux_gnueabihf=arm-linux-gnueabihf-gcc ;;
  esac
fi

# ------------------------------------------------------------- uid sandbox --

# Never an empty array: Bash 3.2 (what macOS runners ship) errors on the
# expansion of one under \`set -u\`, which is a footgun the Linux path never
# reaches because it always fills RUNAS in. \`env\` with no options simply runs
# the command it is given.
RUNAS=(env)
SANDBOXED=no
if [ "\${THERMITE_SANDBOX}" = "uid" ] && command -v sudo >/dev/null 2>&1; then
  if id pourer >/dev/null 2>&1 || sudo -n useradd -m -s /bin/bash pourer 2>/dev/null; then
    sudo -n chmod a+rx "$HOME" 2>/dev/null || true
    sudo -n chmod -R a+rX "$HOME/.rustup" "$HOME/.cargo" 2>/dev/null || true
    sudo -n mkdir -p /home/pourer/.cargo 2>/dev/null || true
    sudo -n chown -R pourer /home/pourer "$SRC" 2>/dev/null || true
    RUNAS=()
    RUNAS=(sudo -n -u pourer env -i
      "HOME=/home/pourer"
      "PATH=\${HOME}/.cargo/bin:/usr/local/bin:/usr/bin:/bin"
      "RUSTUP_HOME=\${HOME}/.rustup"
      "CARGO_HOME=/home/pourer/.cargo"
      "CARGO_TERM_COLOR=always"
      "CARGO_NET_RETRY=3"
      "TERM=xterm-256color")
    if [ -n "$TRIPLE_ENV" ]; then RUNAS+=("\${TRIPLE_ENV}=\${THERMITE_LINKER}"); fi
    if [ -n "\${CC_x86_64_unknown_linux_musl:-}" ]; then RUNAS+=("CC_x86_64_unknown_linux_musl=musl-gcc"); fi
    SANDBOXED=yes
    say "  sandbox  separate unprivileged user"
  fi
fi
if [ "$SANDBOXED" = no ]; then say "  sandbox  none (native \${RUNNER_OS} runner — see repo README)"; fi
say ""

# ----------------------------------------------------------------- compile --

export CARGO_TERM_COLOR=always CARGO_NET_RETRY=3 RUST_BACKTRACE=0
mkdir -p out
mark "compiling"
STATUS=0

if [ -z "$ENTRY" ]; then
  say "No entrypoint was resolved for this pour. The charge was not unsealed."
  exit 93
fi

if [ "\${THERMITE_PROJECT_TYPE}" = "cargo" ]; then
  say "\\$ cargo +\${THERMITE_TOOLCHAIN} build --release --target \${THERMITE_TARGET}"
  say ""
  # stderr — the human stream (Compiling…, warnings, errors) — goes to the tee.
  # stdout — the machine stream (JSON artifact records) — goes to a file.
  "\${RUNAS[@]}" cargo "+\${THERMITE_TOOLCHAIN}" build \\
      --release \\
      --target "\${THERMITE_TARGET}" \\
      --manifest-path "\${SRC}/Cargo.toml" \\
      --message-format=json-render-diagnostics \\
      2>&1 1>cargo-messages.json | pipe
  STATUS=\${PIPESTATUS[0]}
else
  BIN="out/\${THERMITE_NAME}\${THERMITE_EXT}"
  say "\\$ rustc +\${THERMITE_TOOLCHAIN} --edition 2021 -O --target \${THERMITE_TARGET} -o \${BIN} \${ENTRY}"
  say ""
  "\${RUNAS[@]}" rustc "+\${THERMITE_TOOLCHAIN}" --edition 2021 -O \\
      --color always \\
      --target "\${THERMITE_TARGET}" \\
      -o "$BIN" "\${JOB_DIR}/\${ENTRY}" 2>&1 | pipe
  STATUS=\${PIPESTATUS[0]}
fi

say ""
if [ "$STATUS" -ne 0 ]; then
  mark "failed:\${STATUS}"
  say "Compilation failed. Exit code \${STATUS}."
  exit "$STATUS"
fi

mark "linking"
say "Compiled clean. Casting the ingot."
exit 0
`,
  "scripts/sweep.mjs": `#!/usr/bin/env node
// THERMITE — sweep.mjs
//
// Remove spent pours about 24 hours after they were submitted.
//
// The one rule that matters: never touch a pour whose run has not finished.
// Age alone is not sufficient evidence — a 25-minute build submitted 23h50m
// ago will still be running when the sweep starts. Liveness is checked against
// the Actions API at sweep time, per pour, and anything not clearly completed
// is left exactly where it is.

import { execFileSync } from 'node:child_process';
import { readdirSync, existsSync, readFileSync } from 'node:fs';

const API = process.env.GITHUB_API_URL || 'https://api.github.com';
const REPO = process.env.GITHUB_REPOSITORY;
const TOKEN = process.env.GITHUB_TOKEN;
const BRANCH_LOGS = 'crucible-logs';
const MAX_AGE_MS = 24 * 60 * 60 * 1000;
const SETTLE_MS = 30 * 60 * 1000;   // grace before assuming "no run will appear"
const STALE_STREAM_MS = 10 * 60 * 1000;
const DRY = process.env.THERMITE_DRY_RUN === 'true';

const git = (...a) => execFileSync('git', a, { encoding: 'utf8' }).trim();
const log = (...a) => console.log('[sweep]', ...a);

async function api(path, init = {}) {
  for (let i = 0; i < 4; i++) {
    const res = await fetch(\`\${API}\${path}\`, {
      ...init,
      headers: {
        Authorization: \`Bearer \${TOKEN}\`,
        Accept: 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
        'User-Agent': 'thermite-sweep',
        ...(init.body ? { 'Content-Type': 'application/json' } : {}),
      },
    });
    if (res.status === 403 || res.status === 429) {
      const wait = Number(res.headers.get('retry-after') || 10);
      await new Promise((r) => setTimeout(r, wait * 1000));
      continue;
    }
    if (res.status >= 500) { await new Promise((r) => setTimeout(r, 1000 * (i + 1))); continue; }
    return res;
  }
  return { ok: false, status: 599, json: async () => ({}) };
}

// --------------------------------------------------------------------------

if (!existsSync('jobs')) { log('no jobs directory; nothing to sweep'); process.exit(0); }

const ids = readdirSync('jobs', { withFileTypes: true })
  .filter((e) => e.isDirectory() && /^[0-9A-HJKMNP-TV-Z]{26}$/.test(e.name))
  .map((e) => e.name);

if (!ids.length) { log('no pours on disk'); process.exit(0); }
log(\`\${ids.length} pour(s) present\`);

const now = Date.now();
const removable = [];
const kept = [];

for (const id of ids) {
  // The commit that ADDED the manifest is exactly the commit that triggered
  // the run. Same key on both sides of the join, so it cannot drift.
  let sha = '', when = '';
  try {
    const line = git('log', '--diff-filter=A', '--format=%H %cI', '-1', '--', \`jobs/\${id}/manifest.json\`);
    [sha, when] = line.split(' ');
  } catch { /* ignore */ }

  if (!sha) { kept.push([id, 'cannot resolve the commit that created it']); continue; }

  const age = now - Date.parse(when);

  // Per-pour cleanup policy, declared at submission time.
  //   expire    (default) — 24 hours, whatever happened
  //   onSuccess           — eligible as soon as a successful run has completed
  //   onReturn            — the browser deletes it once the ingot has been
  //                         retrieved and, if sealed, decrypted; the sweep only
  //                         acts as the 24-hour backstop
  // onFailure: 'clean' lets a failed pour go early. The default keeps it,
  // because a failed build's log is usually the only thing worth having.
  let policy = 'expire';
  let onFailure = 'keep';
  try {
    const m = JSON.parse(readFileSync(\`jobs/\${id}/manifest.json\`, 'utf8'));
    if (m.cleanup?.policy) policy = m.cleanup.policy;
    if (m.cleanup?.onFailure) onFailure = m.cleanup.onFailure;
  } catch { /* unreadable manifest falls back to the safest policy */ }

  const early = policy === 'onSuccess' || onFailure === 'clean';
  if (age < MAX_AGE_MS && !early) {
    kept.push([id, \`only \${(age / 3600000).toFixed(1)}h old\`]);
    continue;
  }

  // --- liveness, the part that must not be wrong -------------------------
  const res = await api(\`/repos/\${REPO}/actions/runs?head_sha=\${sha}&per_page=100\`);
  if (!res.ok) { kept.push([id, \`run status unavailable (HTTP \${res.status})\`]); continue; }
  const runs = (await res.json()).workflow_runs || [];

  if (runs.length === 0) {
    if (age < MAX_AGE_MS + SETTLE_MS) { kept.push([id, 'no run yet; still inside the grace window']); continue; }
    log(\`\${id}: no run was ever created; treating as abandoned\`);
  } else {
    const live = runs.filter((r) => r.status !== 'completed');
    if (live.length) {
      kept.push([id, \`run \${live[0].id} is \${live[0].status}\`]);
      continue;
    }

    // Early policies only apply to the outcome they name.
    if (age < MAX_AGE_MS) {
      const succeeded = runs.some((r) => r.conclusion === 'success');
      const failed = runs.some((r) => ['failure', 'timed_out', 'startup_failure'].includes(r.conclusion));
      const eligible = (policy === 'onSuccess' && succeeded) || (onFailure === 'clean' && failed);
      if (!eligible) {
        kept.push([id, \`policy \${policy}/\${onFailure} does not release it yet\`]);
        continue;
      }
    }
  }

  // --- second opinion: is the log stream still being written? ------------
  const st = await api(\`/repos/\${REPO}/contents/logs/\${id}.state.json?ref=\${BRANCH_LOGS}\`);
  if (st.ok) {
    try {
      const meta = await st.json();
      const state = JSON.parse(Buffer.from(meta.content, 'base64').toString('utf8'));
      if (state.live && now - Date.parse(state.updatedAt) < STALE_STREAM_MS) {
        kept.push([id, 'log stream is still live']);
        continue;
      }
    } catch { /* unreadable state is not a reason to keep it forever */ }
  }

  removable.push({ id, sha });
}

for (const [id, why] of kept) log(\`keep   \${id} — \${why}\`);
for (const { id } of removable) log(\`sweep  \${id}\`);

if (!removable.length) { log('nothing to remove'); process.exit(0); }
if (DRY) { log('dry run; stopping here'); process.exit(0); }

// ------------------------------------------------- releases, tags, logs -----

for (const { id } of removable) {
  const tag = \`pour-\${id}\`;
  const rel = await api(\`/repos/\${REPO}/releases/tags/\${tag}\`);
  if (rel.ok) {
    const { id: releaseId } = await rel.json();
    await api(\`/repos/\${REPO}/releases/\${releaseId}\`, { method: 'DELETE' });
    await api(\`/repos/\${REPO}/git/refs/tags/\${tag}\`, { method: 'DELETE' });
    log(\`removed release \${tag}\`);
  }
  for (const path of [\`logs/\${id}.log\`, \`logs/\${id}.log.tenc\`, \`logs/\${id}.state.json\`]) {
    const head = await api(\`/repos/\${REPO}/contents/\${path}?ref=\${BRANCH_LOGS}\`);
    if (!head.ok) continue;
    const { sha } = await head.json();
    await api(\`/repos/\${REPO}/contents/\${path}\`, {
      method: 'DELETE',
      body: JSON.stringify({ message: \`thermite: sweep \${id} logs [skip ci]\`, sha, branch: BRANCH_LOGS }),
    });
  }
}

// --------------------------------------------------- one deletion commit ----

execFileSync('git', ['config', 'user.name', 'thermite[bot]']);
execFileSync('git', ['config', 'user.email', 'thermite[bot]@users.noreply.github.com']);
for (const { id } of removable) execFileSync('git', ['rm', '-r', '-q', '--', \`jobs/\${id}\`]);

const message = \`thermite: sweep \${removable.length} spent pour\${removable.length > 1 ? 's' : ''} [skip ci]\`;
execFileSync('git', ['commit', '-q', '-m', message]);

for (let i = 0; i < 4; i++) {
  try { execFileSync('git', ['push', 'origin', 'HEAD:main'], { stdio: 'inherit' }); break; }
  catch {
    // A pour landed while we were sweeping. Rebase onto it and try again;
    // the deletions are independent of whatever was just added.
    execFileSync('git', ['fetch', 'origin', 'main'], { stdio: 'inherit' });
    execFileSync('git', ['rebase', 'origin/main'], { stdio: 'inherit' });
  }
}

log(\`removed \${removable.length} pour(s)\`);

// If the crucible is completely empty, reset the log branch to a fresh orphan
// commit so its history can never grow without bound.
if (removable.length === ids.length) {
  const empty = await api(\`/repos/\${REPO}/git/trees\`, { method: 'POST', body: JSON.stringify({ tree: [] }) });
  if (empty.ok) {
    const tree = (await empty.json()).sha;
    const c = await api(\`/repos/\${REPO}/git/commits\`, {
      method: 'POST',
      body: JSON.stringify({ message: 'thermite: cold crucible [skip ci]', tree, parents: [] }),
    });
    if (c.ok) {
      await api(\`/repos/\${REPO}/git/refs/heads/\${BRANCH_LOGS}\`, {
        method: 'PATCH',
        body: JSON.stringify({ sha: (await c.json()).sha, force: true }),
      });
      log('log branch reset to an empty orphan commit');
    }
  }
}
`,
  "README.md": `# thermite-crucible

This repository is a **build crucible**. Thermite created it on your GitHub
account so that your Rust compilations run on GitHub's own hosted runners,
under your account, using your quota, with nothing of anyone else's in the loop.

It is public on purpose: Actions minutes are unmetered for public repositories,
and metered for private ones.

## What lives here

\`\`\`
jobs/<POUR-ID>/          one submission — manifest.json + source/
.github/workflows/       build.yml (push → jobs/**) and cleanup.yml (cron)
scripts/                 the compiler driver and the housekeeping
\`\`\`

Plus two things that are not files on \`main\`:

- branch **\`crucible-logs\`** — live build output, written every 2.5 s while a
  pour runs, so the website can show you the log as it happens. GitHub's own
  log endpoint cannot be read from a browser; this is the way around that.
- releases **\`pour-<POUR-ID>\`** — the finished binary, with a plain download
  URL that needs no token.

## Encryption (optional)

If you set up encrypted pours, two more things live here:

\`\`\`
.thermite/keys/source-public.pem     public — used by your browser to seal source
.thermite/keys/artifact-public.pem   public — used by the runner to seal your ingot
\`\`\`

Both are public keys and are safe in a public repository. **No private key belongs
in this repository, ever.**

- The **source private key** goes in Settings → Secrets and variables → Actions,
  named exactly \`THERMITE_SOURCE_KEY\`. Only the \`Unseal the charge\` step sees it,
  and that step finishes before the compiler starts — so by the time your
  \`build.rs\` runs, the process holding the key is gone.
- The **artifact private key** never comes near this repository. It stays with
  you, and it is the only thing that can open your sealed ingots and logs.
  Nobody can recover it for you.

On a sealed pour, compiler output does not go to the Actions job log at all
(that log is public on a public repository). It goes only into the encrypted log
on the \`crucible-logs\` branch.

## Housekeeping

\`Thermite sweep\` runs every six hours and removes pours older than 24 hours,
along with their logs and releases. **It never touches a pour whose run has not
finished** — it checks the Actions API for liveness before deleting anything.

You can run it by hand from the Actions tab, with a dry-run option. Each pour can
also carry its own policy — clean up on success, clean up once the ingot has been
retrieved, or the default 24 hours — and the website can clean up individual
pours on demand.

Note that GitHub keeps some things Thermite cannot delete: Actions run records
and their job logs (~90 days), Actions artifacts until their own expiry, and Git
history, which retains the commit that added a pour even after its files are
removed.

## What a pour can and cannot do

Your submitted code is compiled here, and compiling Rust runs arbitrary code:
\`build.rs\`, procedural macros, and anything they invoke.

**Cannot:**

- change any workflow in this repository. GitHub refuses workflow file writes
  from an Actions token, so a malicious \`build.rs\` cannot rewrite \`build.yml\`
  to escalate.
- reach any other repository. \`GITHUB_TOKEN\` is scoped to this repo alone and
  expires when the job ends.
- read a secret. This repository has no secrets, and none should ever be added
  to it.
- use a third-party action. Actions permissions here are set to GitHub-owned
  actions only.

**Can, in the worst case:** on **Windows and macOS** runners, read the
short-lived \`GITHUB_TOKEN\` out of the log relay's process environment and use
it to write to *this* repository — a disposable build repo that holds nothing
but throwaway jobs. On **Linux** runners the compile runs as a separate
unprivileged local user, which closes that path at the kernel level.

If that residual risk matters to you, prefer the Linux targets, or delete this
repository when you are done with it. Deleting it costs nothing; Thermite will
offer to build a new one next time you pour.

## Deleting this repository

Settings → General → Danger Zone → Delete this repository. Nothing else of
yours is affected.
`,
  ".gitignore": `pour.log
pour.done
relay.out
relay.pid
cargo-messages.json
pour-result.json
ingot/
out/
**/target/
`,
};

export const TEMPLATE_PATHS = Object.keys(TEMPLATE);
